[package]
name = "lab1"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"

[dev-dependencies]
divan = "0.1.21"
proptest = "1.7.0"
rand = "0.9.2"

[[bench]]
name = "product"
harness = false

[profile.release]
debug = true
